export const RUTA = [
  {
    "OrdenServicio": "string",
    "Vehiculo": "string",
    "Fecha": "Datetime",
    "Conductor": "string",
    "Cliente": "string",
    "Descripcion": "string",
    "Etapa": "string",
    "Progreso": "int",
    "Aprobar": "int",
    "Calle": "string",
    "Ciudad": "string",
    "Provincia": "string",
    "NumeroCalle": "string",
    "ComplementoDireccion": "string",
    "CodigoPostal": "string",
    "ServiceDetails": [
      {
        "NumLinea": "double",
        "TipoTransaccion": "int",
        "Cantidad": "double",
        "CodUnidad": "string",
        "ReferenciaResiduo": "string",
        "CategoriaResiduo": "string",
        "DimensionInventario": "string",
        "DescripcionResiduo": "string",
        "DCSConsejeria": "string",
        "ReferenciaEnvase": "string",
        "CodUnidadEnvase": "string",
        "CantidadEnvase": "string",
        "NumAceptacion": "string",
        "NumDCS": "string",
        "Gestor": "string",
        "Transportista": "string",
        "NumNotificacion": "string",
        "NumAdmision": "string",
        "Observaciones": "string"
      },
    ]
  }, {
    "OrdenServicio": "string",
    "Vehiculo": "string",
    "Fecha": "Datetime",
    "Conductor": "string",
    "Cliente": "string",
    "Descripcion": "string",
    "Etapa": "string",
    "Progreso": "int",
    "Aprobar": "int",
    "Calle": "string",
    "Ciudad": "string",
    "Provincia": "string",
    "NumeroCalle": "string",
    "ComplementoDireccion": "string",
    "CodigoPostal": "string",
    "ServiceDetails": [
      {
        "NumLinea": "double",
        "TipoTransaccion": "int",
        "Cantidad": "double",
        "CodUnidad": "string",
        "ReferenciaResiduo": "string",
        "CategoriaResiduo": "string",
        "DimensionInventario": "string",
        "DescripcionResiduo": "string",
        "DCSConsejeria": "string",
        "ReferenciaEnvase": "string",
        "CodUnidadEnvase": "string",
        "CantidadEnvase": "string",
        "NumAceptacion": "string",
        "NumDCS": "string",
        "Gestor": "string",
        "Transportista": "string",
        "NumNotificacion": "string",
        "NumAdmision": "string",
        "Observaciones": "string"
      },
    ]
  }
];